apiVersion: apps/v1
kind: Deployment
metadata:
  name: cumulusbankodmsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cumulusbankodmsvc
  template:
    metadata:
      labels:
        name: cumulusbankodmsvc
    spec:
      serviceAccountName: cumulusbankodmsvc
      containers:
        - name: cumulusbankodmsvc
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cumulusbankodmsvc"
