replicaCount: 2

metadata:
 name: odmbanksvc 
 label: odmbanksvc

readinessProbe:
  path: /healthz
  port: 3005
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 3005
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
image:
  name: odmbanksvc
  imageName: "mycluster.icp:8500/default/odm-microservice:0.0.1" 
  imagePullPolicy: Always
  ports:
    containerPort: 3005
  requests:
    cpu: "50m"
    memory: "300Mi"
  limits:
    cpu: "100m"
    memory: "400Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
hpa:
  metadata:
    name: odmbanksvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
  scaleTargetRef:  
    name: odmbanksvc

envOfSecrets:
  envSECRET:
    name: SECRET
    secretKeyRef:
      name: mysecret
      key: SECRET

envOfConfigmaps:
  envODM:
    name: ODM
    configMapKeyRef:
      name: env-database-cumulus
      key: ODM


service:
  serviceMetadata:
    name: odmbanksvc
    labels:
      app: odmbanksvc
  selector:
    selectorName: odmbanksvc
  servicePortConfiguration:
    protocol: TCP
    name: odmbanksvc
    type: ClusterIP
    port: 3005
    targetPort: 3005
