apiVersion: v1
kind: ConfigMap
metadata:
  name: env-database-cumulus
  namespace: {{ .Values.namespace }} 
data:
  ODM: 'http://md-cumulus-cumulusbank-odm-gcp1-odm.cumulusbank:9060/DecisionService/rest/BankingDemo/1.0/getCreditCardOffers/1.0'